chore: check that wpa_supplicant is running

diff --git a/bin/service-on b/bin/service-on
--- a/bin/service-on
+++ b/bin/service-on
@@ -93,6 +93,11 @@ main() {
             echo "Failed to start wpa_supplicant"
             return 1
         fi
+
+        if ! pgrep wpa_supplicant; then
+            echo "Failed to start wpa_supplicant"
+            return 1
+        fi
         udhcpc -i wlan0 &
         set +x
     elif [ "$PLATFORM" = "rg35xxplus" ]; then
